# Basic site settings
title: "James Zhong's Personal Website"
description: "Post-doc at Standford | Mathematics and Statistics"
url: "https://jameszhong.github.io" # Your site URL
baseurl: "" # Leave blank for root

# Author details
author:
  name: "James Zhong"
  email: ""
  bio: "specializing in Mathematics and Data Science"
  avatar: "assets/images/avatar.jpg" # Optional: Add your image here

# Plugins and features
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

# Theme settings
theme: "minimal-mistakes-jekyll" # Replace with your theme if different
minimal_mistakes_skin: "default"

# Sidebar and navigation (adjust as needed)
sidebar:
  nav: false # Set to false if you're not using a navigation menu

# Collections (disable unused ones)
collections:
  posts:
    output: false
  publications:
    output: false
  talks:
    output: false
  teaching:
    output: false
  portfolio:
    output: false

# Optional: Analytics or tracking
google_analytics: "UA-XXXXXXXX-X" # Replace with your Analytics ID if needed

# Markdown configuration
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
